version: "3.5"

services:
  frontend:
    image: example-frontend:latest
    ports:
      - 5000:5000
  backend:
    image: example-backend:latest
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
  redis:
    image: redis:6.2.2
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
        POSTGRES_PASSWORD: example
    volumes:
        - database:/var/lib/postgresql/data

volumes:
    database: