version: "3.5"

services:
  frontend:
    image: example-frontend:latest
    ports:
      - 5000:5000
  backend:
    image: example-backend:latest
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:6.2.2
